services:
  mysql-tc-grupo8:
    image: mysql:8.3
    container_name: container-mysql
    ports:
      - "3306:3306"
    networks:
      tc-grupo8-net:
        aliases:
          - mysql-tc-grupo8
    environment:
      MYSQL_ROOT_PASSWORD: rootAdm123
      MYSQL_DATABASE: db-tc-grupo8
      MYSQL_USER: adm123
      MYSQL_PASSWORD: adm123

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container-ms-login
    ports:
      - "9207:9207"
    depends_on:
      - mysql-tc-grupo8
    networks:
      - tc-grupo8-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-tc-grupo8:3306/db-tc-grupo8?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: adm123
      SPRING_DATASOURCE_PASSWORD: adm123

networks:
  tc-grupo8-net: